---

name: build

on:
  workflow_call:
    inputs:
      # Required inputs
      platforms:
        description: "List of platforms to build images for"
        required: true
        type: string
      build_args:
        description: "Build args to pass to the Dockerfile"
        required: true
        type: string
      image_tags:
        description: "Tags to apply to the image"
        default: local/test-image:latest
        required: true
        type: string
    secrets:
      dockerhub_username:
        description: "Username for Dockerhub access"
        required: true
      dockerhub_token:
        description: "Token for DockerHub access"
        required: true

jobs:

  build-push:
    name: "Build and push container image"
    # Supported Runner Images: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.dockerhub_username }}
        password: ${{ secrets.dockerhub_token }}

    - name: Setup Docker QEMU
      uses: docker/setup-qemu-action@v2.1.0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push container images
      uses: docker/build-push-action@v4
      with:
        push: false
        tags: ${{ inputs.image_tags }}
        build-args: ${{ inputs.build_args }}
        platforms: ${{ inputs.platforms }}
      #run: docker build . --file Dockerfile --tag test:$(date +%s) --build-arg OONIPROBE_VERSION=3.16.3