---

name: logic

on:
  push:
#    branches:
#      - main
    tags:
      - '*'

jobs:

  config:
    name: "Config"
    uses: ./.github/workflows/_config.yml

  build:
    uses: ./.github/workflows/build.yml
    needs: [config]
    with:
      platforms: ${{ needs.config.outputs.platforms }}
      image_tags: ${{ needs.config.outputs.image_tags }}
      build_args: |
        OONIPROBE_VERSION=${{ needs.config.outputs.version }}
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}